# Site settings
title: Marta Toomer Animal Illustration
description: Illustration, drawing and  paintings
keywords: illustration, painting, animal portraits
author: Marta
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.martatoomer.co.uk" # the base hostname & protocol for your site
